services:
  docker-manager:
<<<<<<< Updated upstream
    build: .
    image: virtuaworld/docker-manager:latest
=======
    image: docker-manager-arm:latest
>>>>>>> Stashed changes
    container_name: docker-manager
    ports:
      - "5000-5050:5000-5050"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
<<<<<<< Updated upstream
      - SERVER_IP=192.168.0.2
=======
      - SERVER_IP=192.168.0.26
>>>>>>> Stashed changes
    volumes:
      - /home/virtua/docker:/root/projects-docker-compose
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - web

networks:
  web:
    external: true

