services:
  docker-manager:
    build: .
    image: virtuaworld/docker-manager-arm:latest
    container_name: docker-manager
    ports:
      - "5000-5050:5000-5050"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - SERVER_IP=192.168.x.x
    volumes:
      - /home/user/docker:/root/projects-docker-compose
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
